eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/users/   
        
test:
  input: 4000   

   
logging:
  logback:
    rollingpolicy:
      file-name-pattern:{/Users/samuelkawuma/Library/Mobile Documents/com~apple~CloudDocs/Micro_Services_SpringBoot/logs/ecom_log}

